### ISSUE TITLE
OSError Function not implemented (nicklaus)

### ISSUE THREAD

**Issue by thefeiter** [lineageos4microg/docker-lineage-cicd#112]
Hi there,

I am trying o build for Motorola E4 Plus (nicklaus) with:

```
docker run \
    -e "BRANCH_NAME=lineage-17.1" \
    -e "DEVICE_LIST=nicklaus" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/lineage:/srv/src" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/zips:/srv/zips" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/logs:/srv/logs" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/cache:/srv/ccache" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/keys:/srv/keys" \
    -v "/media/marvin/FILME_USW/docker-lineage-cicd/NICKLAUS/manifests:/srv/local_manifests" \
    --entrypoint bash \
    -it \
    lineageos4microg/docker-lineage-cicd
```

nicklaus.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="LineageOS-MediaTek/android_device_motorola_nicklaus" path="device/motorola/nicklaus" remote="github" />
  <project name="LineageOS-MediaTek/android_device_mediatek_mt6737-common" path="device/mediatek/mt6737-common" remote="github" />
  <project name="LineageOS-MediaTek/proprietary_vendor_motorola" path="vendor/motorola" remote="github" />
  <project name="SamarV-121/android_kernel_motorola_nicklaus" path="kernel/motorola/nickalaus" remote="github" />
  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github" />
  <project name="LineageOS/android_vendor_lineage"  remote="github" />
</manifest>
```

And I am getting the following Error messages:

```
Traceback (most recent call last):
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 628, in <module>
    _Main(sys.argv[1:])
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 602, in _Main
    result = run()
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 595, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 264, in _Run
    result = cmd.Execute(copts, cargs)
  File "/srv/src/LINEAGE_17_1/.repo/repo/subcmds/sync.py", line 874, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/srv/src/LINEAGE_17_1/.repo/repo/subcmds/sync.py", line 781, in _UpdateManifestProject
    success = mp.Sync_NetworkHalf(quiet=opt.quiet, verbose=opt.verbose,
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 1499, in Sync_NetworkHalf
    self._InitGitDir(force_sync=force_sync, quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2853, in _InitGitDir
    self._UpdateHooks(quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2874, in _UpdateHooks
    self._InitHooks(quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2905, in _InitHooks
    platform_utils.symlink(
  File "/srv/src/LINEAGE_17_1/.repo/repo/platform_utils.py", line 212, in symlink
    return os.symlink(source, link_name)
OSError: [Errno 38] Function not implemented: '../../repo/hooks/pre-auto-gc' -> '/srv/src/LINEAGE_17_1/.repo/manifests.git/hooks/pre-auto-gc'
root@70fe1448b19a:/srv/src/LINEAGE_17_1# repo sync -c --force-sync
Traceback (most recent call last):
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 628, in <module>
    _Main(sys.argv[1:])
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 602, in _Main
    result = run()
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 595, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/srv/src/LINEAGE_17_1/.repo/repo/main.py", line 264, in _Run
    result = cmd.Execute(copts, cargs)
  File "/srv/src/LINEAGE_17_1/.repo/repo/subcmds/sync.py", line 874, in Execute
    self._UpdateManifestProject(opt, mp, manifest_name)
  File "/srv/src/LINEAGE_17_1/.repo/repo/subcmds/sync.py", line 781, in _UpdateManifestProject
    success = mp.Sync_NetworkHalf(quiet=opt.quiet, verbose=opt.verbose,
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 1499, in Sync_NetworkHalf
    self._InitGitDir(force_sync=force_sync, quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2853, in _InitGitDir
    self._UpdateHooks(quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2874, in _UpdateHooks
    self._InitHooks(quiet=quiet)
  File "/srv/src/LINEAGE_17_1/.repo/repo/project.py", line 2905, in _InitHooks
    platform_utils.symlink(
  File "/srv/src/LINEAGE_17_1/.repo/repo/platform_utils.py", line 212, in symlink
    return os.symlink(source, link_name)
OSError: [Errno 38] Function not implemented: '../../repo/hooks/pre-auto-gc' -> '/srv/src/LINEAGE_17_1/.repo/manifests.git/hooks/pre-auto-gc'

```

I have absolutely no Idea what could be the cause for this...

I tried different lineage branches and different nicklaus.xml contents.

**Comment by spolack** [comment]
I'm sorry, but we cant support unofficial trees.
