### ISSUE TITLE
July build  failures

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#438]
1. `channel` (Motorola moto g7 play: errors compiling kernel, related to Power Supply.  Possibly due to new smart charging changes in LOS. Watch out for other G7 models (river lake ocean)
    - problems with /e/OS? latest release is e-1.8.1-r, while other G7 models are on 1.12.2-s
<details>

<summary>Log output</summary>

```

 CC      drivers/media/v4l2-core/v4l2-trace.o
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1441:7: error: duplicate case value 'POWER_SUPPLY_PROP_CHARGING_ENABLED'
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1440:7: note: previous case defined here
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1497:7: error: duplicate case value 'POWER_SUPPLY_PROP_CHARGING_ENABLED'
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1494:7: note: previous case defined here
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1530:7: error: duplicate case value 'POWER_SUPPLY_PROP_CHARGING_ENABLED'
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
../../../../../../kernel/motorola/sdm632/drivers/power/supply/qcom/smb1351-charger.c:1527:7: note: previous case defined here
        case POWER_SUPPLY_PROP_CHARGING_ENABLED:
             ^
3 errors generated.
make[5]: *** [/srv/tmp/merged/kernel/motorola/sdm632/scripts/Makefile.build:342: drivers/power/supply/qcom/smb1351-charger.o] Error 1
<snip>
 CC      drivers/scsi/scsi_error.o
make[4]: *** [/srv/tmp/merged/kernel/motorola/sdm632/scripts/Makefile.build:656: drivers/power/supply/qcom] Error 2
make[3]: *** [/srv/tmp/merged/kernel/motorola/sdm632/scripts/Makefile.build:656: drivers/power/supply] Error 2
make[2]: *** [/srv/tmp/merged/kernel/motorola/sdm632/scripts/Makefile.build:656: drivers/power] Error 2

```

</details>
2. Every device after `rosemary` (`sagit`, `sake`, `starlte`) the build is now failing with the following error:

```.
[  5% 8065/151424] build out/target/product/taimen/obj/ETC/build-manifest_intermediates/build-manifest.xml
FAILED: out/target/product/taimen/obj/ETC/build-manifest_intermediates/build-manifest.xml
/bin/bash -c "(mkdir -p out/target/product/taimen/obj/ETC/build-manifest_intermediates/ ) && (python3 .repo/repo/repo manifest -o - -r | grep -Ev \"proprietary_\" > out/target/product/taimen/obj/ETC/build-manifest_intermediates/build-manifest.xml )"
Traceback (most recent call last):
  File "/srv/tmp/merged/.repo/repo/git_command.py", line 324, in __init__
    p = subprocess.Popen(
  File "/srv/tmp/merged/prebuilts/build-tools/linux-x86/bin/py3-cmd/internal/stdlib/subprocess.py", line 966, in __init__
  File "/srv/tmp/merged/prebuilts/build-tools/linux-x86/bin/py3-cmd/internal/stdlib/subprocess.py", line 1842, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/srv/tmp/merged/kernel/google/gs201/private/devices/google/tangorpro'
....

error.GitError: rev-parse: [Errno 2] No such file or directory: '/srv/tmp/merged/kernel/google/gs201/private/devices/google/tangorpro'
```
3. The final few l-20 builds (`wade` onwards) failed with a different error - `breakfast failed for ...`, and all the l-19 & l-18 builds also failed with that error.

**Comment by petefoth** [comment]
>  Watch out for other G7 models (river lake ocean)
`lake` and `ocean` have both completed OK

Try a manual build when July build is completed

**Comment by petefoth** [comment]
> The final few l-20 builds (wade onwards) failed with a different error - breakfast failed for ..., and all the l-19 & l-18 builds also failed with that error.

The build for wade is fails, because it is a tv box and uses `vendor/partner_gms-tv/` which does not exist. 

All subsequent builds (120,19&18 branches) are failing while fetching files from github, some with `urllib.error.HTTPError: HTTP Error 403: rate limit exceeded`. I believe that after the build failure, the build script is accessing github too often within too short a period (60 calls in one hour is the limit I believe), github is refusing the request, so the next build fails when trying access github - and repeat until all builds have failed :(

Two things need to be done (I think)
1. Disable building for TV boxes (until we have decided how best to support them)
2. Build some kind of delay in to the build script when a build fails, to avoid hitting github rate limits

Neither of these are going to happen in the immediate future. Hopefully we can address at least 1. before the next build run

**Comment by petefoth** [comment]
The failed automated builds for `lineage-20.0` devices caused a chain reaction of failures in the builds for `18.1` and `19.1` devices.

Builds for the `19.1` devices have been manually started and are in progress: `apollon,blueline,bonito,crosshatch,discovery,gauguin,gemini,h830,h850,h870,h872,h910,h918,h990,kirin,liber,ls997,mermaid,miatoll,monet,nash,natrium,parker,pioneer,rs988,sargo,tissot,us996,us996d,us997,vayu,voyager,vs995,z2_plus`

When they are completed (probably in 3 or 4 days time), builds will be started for 
- `18.1` devices : `a5y17lte,a7y17lte,addison,ahannah,albus,bacon,castor,castor_windy,cedric,debx,ether,flox,foster,foster_tab,FP2,ginkgo,griffin,hannah,hlte,hltechn,hltekor,hltetmo,jactivelte,jflteatt,jfltespr,jfltevzw,jfltexx,jfvelte,klte,klteactivexx,klteaio,kltechn,kltechnduo,klteduos,kltedv,kltekdi,kltekor,marlin,montana,oneplus3,porg,porg_tab,rhannah,s3ve3gds,s3ve3gjv,s3ve3gxx,sailfish,shamu,sirius,victara,x2,z3,z3c,zl1`
- the `20.0` devices which were not successfully built automatically (excluding `wade` which, along with other Android-TV devices, is not currently supported): `channel,sagit,sake,starlte,star2lte,sunfish,surya,taimen,TP1803,troika,ursa,vela,~~wade~~,walleye,X00TD,xmsirius,xz2c,Z01R,zippo`

As they complete, the new builds should appear as OTA updates,as well as being available for download from [the download server](https://download.lineage.microg.org/?sort=time&order=desc)

Build progress can monitored on [the matrix channel](https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net)

This issue will be closed when all build have been completed

**Comment by petefoth** [comment]
July builds for all supported devices should now be available [for download ](https://download.lineage.microg.org/) and for OTA updates

In addition, old builds for `bullhead`(15.1) and `capricorn` (16.0), which were built but - as far as I can tell - never uploaded, are also now available in the relevant directories. No idea whether these builds will work, and they definitely won't be repeated :)
