### ISSUE TITLE
Bootloops reported for several devices with December 21.0 builds

### ISSUE THREAD

**Issue by petefoth** [lineageos4microg/docker-lineage-cicd#720]
Affected devices include 
1. Moto one 5g ace `kiev`: see #717 Worked after wipe
2. Xiaomi Mi 11 Lite 5G `renoir`: https://github.com/lineageos4microg/docker-lineage-cicd/issues/710#issuecomment-2562608089  Worked after wipe
3. Google Pixel 4a `sunfish`: see [issues/710#issuecomment-2564300420](https://github.com/lineageos4microg/docker-lineage-cicd/issues/719)
4. OnePlus 11 5G `salami` CPH2451 variant: #719 (but not for all devices - see [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/710#issuecomment-2563727451) & [ working for CPH2449  variant: here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/718#issuecomment-2564305953) )

I have no idea what the issue is, or whether it is different issue on different devices. There is no way the project can investigate as we don't own or have access to an of these devices. But very happy to collate any information or boot logs or any other information others can provide.

**Comment by Carlos-Rocha** [comment]
Maybe related to microg signature spoofing?
I had no problems with the upgrade but microg was updated to 0.3.6 before it. Could it be a factor?

**Comment by petefoth** [comment]
Could be, but I don't understand why thst would cause problems only for some devices, or for some variants of some devices

**Comment by vs49688** [comment]
> Maybe related to microg signature spoofing? I had no problems with the upgrade but microg was updated to 0.3.6 before it. Could it be a factor?

I forgot to mention in https://github.com/lineageos4microg/docker-lineage-cicd/issues/718#issuecomment-2564305953, that's what I did too - the breakage in 0.3.6 is what caused me to look for an update.

**Comment by Lealchimie** [comment]
Hello, i finally managed to install on redfin after failed attempts. It is a bit weird, but maybe it can help to just tell what happened : 
- first original OTA failed and caused bootloop. I had magisk installed and tried to reapply before rebooting, which (I believe) made it impossible to just boot on the other slot.
- trying a clean install after that also caused bootloop
- decided to try iodeOS and used your unofficial build found [here](https://sourceforge.net/projects/pf-custom-roms/files/sunfish/iode-os/) (clean install of course)
- upgraded microG to last stable version
- tried (because why not) to dirty flash the lineage4microg december build on top of iodeOS : it boots and works !

I'm unsure of wether I want to stay with a dirty install like this, maybe I can try updating microG in the november build before dirty flashing the december build to see if that works. Or do you think I wouldn't run into too much problems like this ?

**Comment by Carlos-Rocha** [comment]
Wow...I didn't know about pf-custom-roms based on iodeOS, and there's even a rom for surya, tho microg signature is outdated, right?

**Comment by deckultra734** [comment]
> * upgraded microG to last stable version

This is what unironically made the installation work without bootlooping, you have to update to microg [v0.3.6.244735]https://github.com/microg/GmsCore/releases/tag/v0.3.6.244735) before updating otherwise it just bootloops, a fresh installation of 20241227 would bootloop for some reason.

To update correctly to the december builds you must install an older build, update microg then install the december build otherwise it bootloops.

Magisk doesn't affect the outcome although some modules might break due to android changes.

**Comment by petefoth** [comment]
Thanks all. Your input has allowed me to find the root of the problem.

It looks like the problem was caused when I updated the microG `GmsCore` component in the `android_vendor_partner_gms` repo. I believe that there are errors in the permissions file(s), which don't match the permissions in the `.apk`, causing the devices to fail to boot. If microG was updated before updating, then the updated version (and its permissions files) will take priority over the 'bit-in' version, the permissions will match and the device will boot.

It may take a while to fix, but thanks again for all your help

**Comment by petefoth** [comment]
Problem fixed in this PR in the `android_vendor_partner_gms` repo ['Sort out permissions for updated microG GmsCore #38](https://github.com/lineageos4microg/android_vendor_partner_gms/pull/38)

There's a new build for `xz2c` containing the fix. Fixes for the remaining devices will be along in the next couple of days.

Thank you for your patience :)

**Comment by pokulo** [comment]
Thanks for fixing @petefoth ! My Xiaomi Mi 6 (sagit) was also stuck in a bootloop with the December update. I hope side load updating my phone with next version will simply fix the bootloop. Looking forward to install it.

**Comment by pokulo** [comment]
I just flashed the new update https://download.lineage.microg.org/sagit/lineage-21.0-20241231-microG-sagit.zip to my device, but the bootloop is still looping.

**Comment by petefoth** [comment]
I'll look into that this evening.
In the meantime, please can you try running the following for one boot cycle 
`adb logcat > bootlog.txt` and upload the resulting file?

**Comment by pokulo** [comment]
@petefoth thanks for your efforts. I tried `adb logcat` already, but never got any connection during the bootloop. It worked in the past on a running LOS, but only after confirmation. 
Is there an easy way to get the logs from the recovery shell? I guess for logcat to work I have to change boot config to enable usb debugging by default. But how.. I still have to find out.

**Comment by petefoth** [comment]
> I tried adb logcat already, but never got any connection during the bootloop.

I originally made an `eng` build for debugging, rather than the normal `userdebug`, but then I reverted to the earlier `userdebug` build and it just worked: 
- before the 'spinning circles' animation appeared, `adb logcat` said `waiting for device`
- once the 'spinning circles'  were visible, lg messages started appearing

> Is there an easy way to get the logs from the recovery shell?

There probably is, but I don't know what it is :(

> I guess for logcat to work I have to change boot config to enable usb debugging by default. But how..

Maybe
- install the last working version from November, but don't update microG, stick with the default 0.2.27
- enable developer options, USB debugging and rooted debugging
- start `adb root`
- dirty flash the new build, either via the Updater app, or recovery and `adb sideload`
- reboot with the USB still connected
- start `adb logcat` while the device is booting

If that doesn't work, then I'm fresh out of ideas :( Time to go searching the internet!

The latest builds have been working for me on all the devices I own (`xz2c`, `sunfish`) so I don't think it's a general problem for all devices as the earlier builds were.

Good luck!

**Comment by pokulo** [comment]
> I originally made an eng build for debugging, rather than the normal userdebug, but then I reverted to the earlier userdebug build and it just worked

@petefoth This sounds, as I will have to get my own LOS eng-build working. (I never did my own builds). I am curious, how "easy" it might be. Assuming the main difference is about the debugging features being enabled (https://source.android.com/docs/setup/develop/new-device?hl=de#build-variants), the following approach might also work for the existing system just by using the recovery: https://johannes.truschnigg.info/writing/2022-05_android_bootloop_debugging/

> install the last working version from November

Downgrade does not work, because it says: "Denying OTA because it's a SPL downgrade". My Understanding is, this can not easily be bypassed by design, is it? Have the November build up and running as a fallback would be just fine.

> I don't think it's a general problem for all devices as the earlier builds were.

Yes, apparently. Maybe I also broke my phones system in another way when trying to downgrade to the November version before reading this issue.

**Comment by pokulo** [comment]
>  the following approach might also work for the existing system just by using the recovery: https://johannes.truschnigg.info/writing/2022-05_android_bootloop_debugging/

This actually worked. The logcat log now sais:
```
12-31 02:38:47.969  3654  3654 D AndroidRuntime: Shutting down VM
12-31 02:38:47.969  3654  3654 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
12-31 02:38:47.969  3654  3654 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.google.android.gms (/system/product/priv-app/GmsCore): android.permission.FAKE_PACKAGE_SIGNATURE}
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerServiceImpl.onSystemReady(PermissionManagerServiceImpl.java:4373)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.onSystemReady(PermissionManagerService.java:817)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:4302)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2964)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:980)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:701)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-31 02:38:47.969  3654  3654 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)
```

I digged a little in where `android.permission.FAKE_PACKAGE_SIGNATURE` is used, and found the following MR https://github.com/lineageos4microg/android_vendor_partner_gms/pull/38/files#diff-9c89f07e130c5cdf33212713b6d61a33fd6ff6c6b33c30acdd3ceaa53f892e59L6

So @petefoth, do you have an idea, what is wrong on my side? Do you need more information from the logs or about my device?

**Comment by petefoth** [comment]
> Downgrade does not work, because it says: "Denying OTA because it's a SPL downgrade". My Understanding is, this can not easily be bypassed by design, is it? Have the November build up and running as a fallback would be just fine.

That error comes from the latest custom recovery. To get round it, flash [the recovery image from the November build](https://download.lineage.microg.org/sagit/lineage-21.0-20241125-microG-sagit-recovery.img)
`fastboot flash recovery lineage-21.0-20241125-microG-sagit-recovery.img`. You should then be able to install the November ROM zip file

> This actually worked. The logcat log now sais:
> ...

That's really useful

> do you have an idea, what is wrong on my side? 
Yes, it is a problem with the build - I'll make a new one in the next day or so

**Comment by pokulo** [comment]
@petefoth thanks!

**Comment by pokulo** [comment]
@petefoth The todays update fixed the bootloop for me on sagit. Thanks again.

**Comment by deckultra734** [comment]
20250103 installed without issues but like I said in my issue report, since I had the 20241227 installed as per an earlier post, I'm unsure if this issue is resolved. Hopefully someone else that is having issues previous can provide feedback.

**Comment by petefoth** [comment]
> I'm unsure if this issue is resolved.

I'm pretty confident the issue is fixed: I know what caused it and I have made the needed changes to fix it in the [`android_vendor_partner_gm` repo](https://github.com/lineageos4microg/android_vendor_partner_gms)

I was planning to close the issue when new builds including the fix are available for all devices. Devices that have not yet got a build with the fix in are: `ursa,vela,voyager,wade,walleye,xpeng,xz2c,Z01R,zippo`. The build for `ursa` is in progress, the others should be done today or tomorrow
`

**Comment by petefoth** [comment]
All devices that I know to be affected by this issue have now got new builds with the issue fixed. So I will close this issue
