### ISSUE TITLE
HTTP Error 403 in build_manifest.py

### ISSUE THREAD

**Issue by abba23** [lineageos4microg/docker-lineage-cicd#74]
When I run the build, I get the following error message:

```
Traceback (most recent call last):
  File "build_manifest.py", line 36, in <module>
    source_manifest = urlopen(args.url).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

The problem seems to be that Gitlab doesn't allow access for requests without a user agent header. This could be solved by setting the header for urllib2 or just using the requests library instead.

```
from urllib2 import urlopen, Request

headers = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0",
}
request = Request(args.url, headers=headers)
source_manifest = urlopen(request).read()
```

```
import requests

source_manifest = requests.get(args.url).text
```

**Comment by spolack** [comment]
Fix was merged.
