### ISSUE TITLE
Build for "blueline" failed

### ISSUE THREAD

**Issue by spolack** [lineageos4microg/docker-lineage-cicd#95]
```
2020-08-18 12:46:26 - build_super_image.py - INFO    : Building super image from info dict...
2020-08-18 12:46:26 - common.py - INFO    :   Running: "lpmake --metadata-size 65536 --super-name system --metadata-slots 2 --auto-slot-suffixing --device system:2952790016 --device vendor:805306368 --device product:314572800 --group google_dynamic_partitions:4069523456 --partition system:readonly:0:google_dynamic_partitions --partition vendor:readonly:0:google_dynamic_partitions --partition product:readonly:0:google_dynamic_partitions --sparse --output /srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/super_empty.img"
2020-08-18 12:46:26 - common.py - INFO    : 
2020-08-18 12:46:26 - build_super_image.py - INFO    : Done writing image /srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/super_empty.img
2020-08-18 12:46:26 - add_img_to_target_files - INFO    : 

++++ super split images  ++++


2020-08-18 12:46:26 - build_super_image.py - INFO    : Building super image from extracted target files...
2020-08-18 12:46:26 - common.py - WARNING : Failed to read PRODUCT_SERVICES/build.prop
2020-08-18 12:46:26 - common.py - WARNING : Failed to read PRODUCT_SERVICES/etc/build.prop
2020-08-18 12:46:26 - common.py - WARNING : Failed to read ODM/build.prop
2020-08-18 12:46:26 - common.py - WARNING : Failed to read ODM/etc/build.prop
2020-08-18 12:46:26 - sparse_img.py - INFO    : Total of 724454 4096-byte output blocks in 47 input chunks.
2020-08-18 12:46:26 - sparse_img.py - INFO    : Total of 115269 4096-byte output blocks in 13 input chunks.
2020-08-18 12:46:26 - sparse_img.py - INFO    : Total of 155325 4096-byte output blocks in 13 input chunks.
2020-08-18 12:46:26 - common.py - INFO    :   Running: "lpmake --metadata-size 65536 --super-name system --metadata-slots 2 --auto-slot-suffixing --device system:2952790016 --device vendor:805306368 --device product:314572800 --group google_dynamic_partitions:4069523456 --partition system:readonly:2967363584:google_dynamic_partitions --image system=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/system.img --partition vendor:readonly:472141824:google_dynamic_partitions --image vendor=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/vendor.img --partition product:readonly:636211200:google_dynamic_partitions --image product=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/product.img --sparse --output /srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/OTA"
2020-08-18 12:46:26 - common.py - INFO    : lpmake I 08-18 12:46:26 16105 16105 builder.cpp:937] [liblp]Partition system will resize from 0 bytes to 2967363584 bytes
lpmake I 08-18 12:46:26 16105 16105 builder.cpp:937] [liblp]Partition vendor will resize from 0 bytes to 472141824 bytes
lpmake E 08-18 12:46:26 16105 16105 builder.cpp:568] [liblp]Partition product is part of group google_dynamic_partitions which does not have enough space free (636211200 requested, 3439505408 used out of 4069523456)
Not enough space on device for partition product with size 636211200
2020-08-18 12:46:26 - add_img_to_target_files - ERROR   : 
   ERROR:
Traceback (most recent call last):
  File "build/make/tools/releasetools/add_img_to_target_files", line 963, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/add_img_to_target_files", line 957, in main
    AddImagesToTargetFiles(args[0])
  File "build/make/tools/releasetools/add_img_to_target_files", line 896, in AddImagesToTargetFiles
    AddSuperSplit(output_zip)
  File "build/make/tools/releasetools/add_img_to_target_files", line 684, in AddSuperSplit
    built = build_super_image.BuildSuperImage(OPTIONS.input_tmp, outdir)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 186, in BuildSuperImage
    return BuildSuperImageFromExtractedTargetFiles(inp, out)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 169, in BuildSuperImageFromExtractedTargetFiles
    return BuildSuperImageFromDict(info_dict, out)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 137, in BuildSuperImageFromDict
    common.RunAndCheckOutput(cmd)
  File "/srv/tmp/merged/build/make/tools/releasetools/common.py", line 258, in RunAndCheckOutput
    args, proc.returncode, output))
ExternalError: Failed to run command '['lpmake', '--metadata-size', '65536', '--super-name', 'system', '--metadata-slots', '2', '--auto-slot-suffixing', '--device', 'system:2952790016', '--device', 'vendor:805306368', '--device', 'product:314572800', '--group', 'google_dynamic_partitions:4069523456', '--partition', 'system:readonly:2967363584:google_dynamic_partitions', '--image', 'system=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/system.img', '--partition', 'vendor:readonly:472141824:google_dynamic_partitions', '--image', 'vendor=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/vendor.img', '--partition', 'product:readonly:636211200:google_dynamic_partitions', '--image', 'product=/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/IMAGES/product.img', '--sparse', '--output', '/srv/tmp/merged/out/target/product/blueline/obj/PACKAGING/target_files_intermediates/lineage_blueline-target_files-eng.root/OTA']' (exit code 70):
lpmake I 08-18 12:46:26 16105 16105 builder.cpp:937] [liblp]Partition system will resize from 0 bytes to 2967363584 bytes
lpmake I 08-18 12:46:26 16105 16105 builder.cpp:937] [liblp]Partition vendor will resize from 0 bytes to 472141824 bytes
lpmake E 08-18 12:46:26 16105 16105 builder.cpp:568] [liblp]Partition product is part of group google_dynamic_partitions which does not have enough space free (636211200 requested, 3439505408 used out of 4069523456)
Not enough space on device for partition product with size 636211200

ninja: build stopped: subcommand failed.
12:46:26 ninja failed with: exit status 1
```

**Comment by spolack** [comment]
Build failed again with the same error.

**Comment by chrp** [comment]
@spolack Do you have any idea what one needs to try in order to get lpmake to work?

**Comment by enewbury** [comment]
Unfortunately, I'm a web developer, so not sure I can be very helpful in fixing this, but just noting that I would love to use this build when it's working again :)

**Comment by spolack** [comment]
> Build should success with WITH_GMS=true environment variable set. See: https://github.com/LineageOS/android_device_google_crosshatch/blob/3ecd186d56446ba94e49c860b2e4771555522950/BoardConfigLineage.mk#L22 (same for blueline)
_Originally posted by @okukharchuk in https://github.com/lineageos4microg/docker-lineage-cicd/issues/96#issuecomment-751293575_

That worked. Nice catch! @okukharchuk
