### ISSUE TITLE
Build for "crosshatch" failed

### ISSUE THREAD

**Issue by spolack** [lineageos4microg/docker-lineage-cicd#96]
```
2020-08-18 17:16:44 - sparse_img.py - INFO    : Total of 726370 4096-byte output blocks in 47 input chunks.
2020-08-18 17:16:44 - sparse_img.py - INFO    : Total of 115461 4096-byte output blocks in 13 input chunks.
2020-08-18 17:16:44 - sparse_img.py - INFO    : Total of 155332 4096-byte output blocks in 13 input chunks.
2020-08-18 17:16:44 - common.py - INFO    :   Running: "lpmake --metadata-size 65536 --super-name system --metadata-slots 2 --auto-slot-suffixing --device system:2952790016 --device vendor:805306368 --device product:314572800 --group google_dynamic_partitions:4069523456 --partition system:readonly:2975211520:google_dynamic_partitions --image system=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/system.img --partition vendor:readonly:472928256:google_dynamic_partitions --image vendor=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/vendor.img --partition product:readonly:636239872:google_dynamic_partitions --image product=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/product.img --sparse --output /srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/OTA"
2020-08-18 17:16:44 - common.py - INFO    : lpmake I 08-18 17:16:44 19152 19152 builder.cpp:937] [liblp]Partition system will resize from 0 bytes to 2975211520 bytes
lpmake I 08-18 17:16:44 19152 19152 builder.cpp:937] [liblp]Partition vendor will resize from 0 bytes to 472928256 bytes
lpmake E 08-18 17:16:44 19152 19152 builder.cpp:568] [liblp]Partition product is part of group google_dynamic_partitions which does not have enough space free (636239872 requested, 3448139776 used out of 4069523456)
Not enough space on device for partition product with size 636239872
2020-08-18 17:16:44 - add_img_to_target_files - ERROR   : 
   ERROR:
Traceback (most recent call last):
  File "build/make/tools/releasetools/add_img_to_target_files", line 963, in <module>
    main(sys.argv[1:])
  File "build/make/tools/releasetools/add_img_to_target_files", line 957, in main
    AddImagesToTargetFiles(args[0])
  File "build/make/tools/releasetools/add_img_to_target_files", line 896, in AddImagesToTargetFiles
    AddSuperSplit(output_zip)
  File "build/make/tools/releasetools/add_img_to_target_files", line 684, in AddSuperSplit
    built = build_super_image.BuildSuperImage(OPTIONS.input_tmp, outdir)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 186, in BuildSuperImage
    return BuildSuperImageFromExtractedTargetFiles(inp, out)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 169, in BuildSuperImageFromExtractedTargetFiles
    return BuildSuperImageFromDict(info_dict, out)
  File "/srv/tmp/merged/build/make/tools/releasetools/build_super_image.py", line 137, in BuildSuperImageFromDict
    common.RunAndCheckOutput(cmd)
  File "/srv/tmp/merged/build/make/tools/releasetools/common.py", line 258, in RunAndCheckOutput
    args, proc.returncode, output))
ExternalError: Failed to run command '['lpmake', '--metadata-size', '65536', '--super-name', 'system', '--metadata-slots', '2', '--auto-slot-suffixing', '--device', 'system:2952790016', '--device', 'vendor:805306368', '--device', 'product:314572800', '--group', 'google_dynamic_partitions:4069523456', '--partition', 'system:readonly:2975211520:google_dynamic_partitions', '--image', 'system=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/system.img', '--partition', 'vendor:readonly:472928256:google_dynamic_partitions', '--image', 'vendor=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/vendor.img', '--partition', 'product:readonly:636239872:google_dynamic_partitions', '--image', 'product=/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/IMAGES/product.img', '--sparse', '--output', '/srv/tmp/merged/out/target/product/crosshatch/obj/PACKAGING/target_files_intermediates/lineage_crosshatch-target_files-eng.root/OTA']' (exit code 70):
lpmake I 08-18 17:16:44 19152 19152 builder.cpp:937] [liblp]Partition system will resize from 0 bytes to 2975211520 bytes
lpmake I 08-18 17:16:44 19152 19152 builder.cpp:937] [liblp]Partition vendor will resize from 0 bytes to 472928256 bytes
lpmake E 08-18 17:16:44 19152 19152 builder.cpp:568] [liblp]Partition product is part of group google_dynamic_partitions which does not have enough space free (636239872 requested, 3448139776 used out of 4069523456)
Not enough space on device for partition product with size 636239872

ninja: build stopped: subcommand failed.
17:16:44 ninja failed with: exit status 1

#### failed to build some targets (49:52 (mm:ss)) ####
```

**Comment by spolack** [comment]
Failed again on last build with same error.

**Comment by franckstauffer71** [comment]
It also fails for me but with another log
```
/srv/src/LINEAGE_17_1/kernel/google/msm-4.9/scripts/link-vmlinux.sh: line 93: 16591 Killed                  ${LD} ${LDFLAGS} -r -o ${1} $(modversions) ${objects}
make[1]: *** [/srv/src/LINEAGE_17_1/kernel/google/msm-4.9/Makefile:1105: vmlinux] Error 137
make[1]: Leaving directory '/srv/src/LINEAGE_17_1/out/target/product/crosshatch/obj/KERNEL_OBJ'
make: *** [Makefile:152: sub-make] Error 2
make: Leaving directory '/srv/src/LINEAGE_17_1/kernel/google/msm-4.9'
[ 37% 43175/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioIndicationAll.cpp [arm]
[ 37% 43176/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioAll.cpp
[ 37% 43177/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioAll.cpp
[ 37% 43178/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioResponseAll.cpp
[ 37% 43179/116100] //hardware/interfaces/radio/1.1:android.hardware.radio@1.1 clang++ android/hardware/radio/1.1/SapAll.cpp
[ 37% 43180/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioResponseAll.cpp
[ 37% 43181/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioAll.cpp [arm]
[ 37% 43182/116100] //hardware/interfaces/radio/1.1:android.hardware.radio@1.1 clang++ android/hardware/radio/1.1/RadioIndicationAll.cpp
[ 37% 43183/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioResponseAll.cpp [arm]
[ 37% 43184/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioAll.cpp [arm]
[ 37% 43185/116100] //hardware/interfaces/radio/1.0:android.hardware.radio@1.0 clang++ android/hardware/radio/1.0/RadioResponseAll.cpp [arm]
[ 37% 43186/116100] //hardware/interfaces/radio/1.1:android.hardware.radio@1.1 clang++ android/hardware/radio/1.1/RadioAll.cpp
[ 37% 43187/116100] //hardware/interfaces/radio/1.1:android.hardware.radio@1.1 clang++ android/hardware/radio/1.1/RadioResponseAll.cpp
ninja: build stopped: subcommand failed.
15:35:30 ninja failed with: exit status 1

#### failed to build some targets (01:11:47 (hh:mm:ss)) ####
```

**Comment by okukharchuk** [comment]
Build should success with WITH_GMS=true environment variable set. See: https://github.com/LineageOS/android_device_google_crosshatch/blob/3ecd186d56446ba94e49c860b2e4771555522950/BoardConfigLineage.mk#L22 (same for blueline)

**Comment by spolack** [comment]
Thank you @okukharchuk. That worked for blueline.

Unfortunately that device failed, lets see if it works with next build.

```
[ 99% 1051/1060] including vendor/xiaomi/violet/Android.mk ...
[ 99% 1052/1060] including vendor/xiaomi/wayne-common/Android.mk ...
[ 99% 1053/1060] including vendor/xiaomi/wayne/Android.mk ...
[ 99% 1054/1060] including vendor/xiaomi/whyred/Android.mk ...
[ 99% 1055/1060] including vendor/yandex/Amber/Android.mk ...
[ 99% 1056/1060] including vendor/zuk/ham/Android.mk ...
[ 99% 1057/1060] including vendor/zuk/msm8996-common/Android.mk ...
[ 99% 1058/1060] including vendor/zuk/z2_plus/Android.mk ...
[ 99% 1059/1060] finishing build rules ...
FAILED: 
hardware/qcom/audio/hal/Android.mk: error: "audio.primary.sdm845 (SHARED_LIBRARIES android-arm64) missing libtinycompress (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom/audio/hal/Android.mk: error: "audio.primary.sdm845 (SHARED_LIBRARIES android-arm) missing libtinycompress (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:972: error: exiting from previous errors.
02:22:12 ckati failed with: exit status 1

#### failed to build some targets (01:41 (mm:ss)) ####

>> [Fri Jan  8 02:22:12 UTC 2021] Failed build for crosshatch
>> [Fri Jan  8 02:22:12 UTC 2021] Running post-build.sh for crosshatch
>> [Fri Jan  8 02:22:12 UTC 2021] Finishing build for crosshatch
>> [Fri Jan  8 02:22:17 UTC 2021] Cleaning source dir for device crosshatch
```

**Comment by spolack** [comment]
Last build succeded.
